# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 20m
  tests: false

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
    - unused
    - staticcheck
    - bidichk
    - durationcheck
    - whitespace
    - revive # only certain checks enabled

    ### linters we tried and will not be using:
    ###
    # - structcheck # lots of false positives
    # - errcheck #lot of false positives
    # - contextcheck
    # - errchkjson # lots of false positives
    # - errorlint # this check crashes
    # - exhaustive # silly check
    # - makezero # false positives
    # - nilerr # several intentional

linters-settings:
  gofmt:
    simplify: true
  revive:
    enable-all-rules: false